# Generated by Django 6.0 on 2026-01-07 11:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('treatment_type', models.CharField(choices=[('whitening', 'Teeth Whitening'), ('orthodontics', 'Orthodontics'), ('implant', 'Dental Implant'), ('restoration', 'Restoration'), ('cosmetic', 'Cosmetic Surgery')], max_length=50)),
                ('before_image_url', models.URLField()),
                ('after_image_url', models.URLField()),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('featured_image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='clinic_blog_slug_4a2ea0_idx'), models.Index(fields=['is_published', '-published_at'], name='clinic_blog_is_publ_292c86_idx')],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='clinic_pati_phone_f7f0cb_idx'), models.Index(fields=['email'], name='clinic_pati_email_583a17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('whitening', 'Whitening'), ('orthodontics', 'Orthodontics'), ('implants', 'Implants'), ('cosmetic', 'Cosmetic'), ('restorative', 'Restorative'), ('preventive', 'Preventive')], max_length=50)),
                ('price_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='clinic_serv_is_acti_b2ad3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('services', models.ManyToManyField(related_name='doctors', to='clinic.service')),
            ],
            options={
                'verbose_name_plural': 'Doctors',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('appointment_date', models.DateField(db_index=True)),
                ('appointment_time', models.TimeField()),
                ('queue_number', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.service')),
            ],
            options={
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='clinic.patient')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_rescheduled', 'Appointment Rescheduled')], max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clinic.appointment')),
            ],
            options={
                'ordering': ['-scheduled_time'],
                'indexes': [models.Index(fields=['status', 'scheduled_time'], name='clinic_noti_status_61a8e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_position', models.PositiveIntegerField()),
                ('appointment_date', models.DateField(db_index=True)),
                ('scheduled_start_time', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='clinic.appointment')),
            ],
            options={
                'ordering': ['appointment_date', 'queue_position'],
                'indexes': [models.Index(fields=['appointment_date', 'queue_position'], name='clinic_queu_appoint_a2575f_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueueStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField()),
                ('total_appointments', models.PositiveIntegerField(default=0)),
                ('completed_appointments', models.PositiveIntegerField(default=0)),
                ('cancelled_appointments', models.PositiveIntegerField(default=0)),
                ('average_wait_minutes', models.FloatField(default=0)),
                ('min_wait_minutes', models.PositiveIntegerField(default=0)),
                ('max_wait_minutes', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service')),
            ],
            options={
                'verbose_name_plural': 'Queue Statistics',
                'ordering': ['-appointment_date'],
                'unique_together': {('service', 'appointment_date')},
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['booking_id'], name='clinic_appo_booking_707411_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_date'], name='clinic_appo_patient_616a63_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'appointment_time'], name='clinic_appo_appoint_0703a0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='clinic_appo_status_7ffd30_idx'),
        ),
    ]
