# Generated by Django 6.0 on 2025-12-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='service',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='text',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='comment',
            field=models.TextField(default='', verbose_name='التعليق'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='patient_name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم المريض'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='service_name',
            field=models.CharField(default='', max_length=200, verbose_name='اسم الخدمة'),
        ),
    ]
