# Generated by Django 6.0 on 2025-12-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_testimonial_image_remove_testimonial_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الصورة'),
        ),
    ]
