# Generated by Django 6.0 on 2025-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfterGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('treatment_type', models.CharField(choices=[('whitening', 'تبييض الأسنان'), ('veneers', 'القشور'), ('implants', 'زراعة الأسنان'), ('orthodontics', 'تقويم الأسنان'), ('cosmetic', 'تجميل الأسنان'), ('other', 'أخرى')], max_length=50, verbose_name='نوع العلاج')),
                ('before_image', models.ImageField(upload_to='gallery/before/', verbose_name='صورة قبل')),
                ('after_image', models.ImageField(upload_to='gallery/after/', verbose_name='صورة بعد')),
                ('patient_age', models.IntegerField(blank=True, null=True, verbose_name='عمر المريض')),
                ('treatment_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدة العلاج')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صورة قبل وبعد',
                'verbose_name_plural': 'معرض قبل وبعد',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
