# Generated by Django 6.0 on 2026-01-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_clinic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
