# Generated by Django 6.0 on 2025-12-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_beforeaftergallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='معرف الحجز'),
        ),
    ]
