# Generated by Django 6.0 on 2025-12-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_appointment_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queue_number',
            field=models.IntegerField(default=0, verbose_name='رقم الطابور'),
        ),
    ]
