# Generated by Django 6.0 on 2025-12-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_appointment_queue_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'رسالة نصية'), ('email', 'بريد إلكتروني'), ('whatsapp', 'واتساب')], max_length=20, verbose_name='نوع الإشعار')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('sent', 'تم الإرسال'), ('failed', 'فشل الإرسال')], default='pending', max_length=20, verbose_name='الحالة')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('recipient', models.CharField(help_text='رقم هاتف أو بريد إلكتروني', max_length=255, verbose_name='المستقبل')),
                ('scheduled_time', models.DateTimeField(verbose_name='وقت الإرسال المجدول')),
                ('sent_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال الفعلي')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clinic.appointment', verbose_name='الموعد')),
            ],
            options={
                'verbose_name': 'إشعار موعد',
                'verbose_name_plural': 'إشعارات المواعيد',
                'ordering': ['-created_at'],
            },
        ),
    ]
