# Generated by Django 6.0 on 2025-12-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_appointmentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start_time', models.DateTimeField(verbose_name='وقت البدء المجدول')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء الفعلي')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء الفعلي')),
                ('estimated_wait_minutes', models.IntegerField(default=0, verbose_name='الانتظار المتوقع (دقيقة)')),
                ('actual_wait_minutes', models.IntegerField(blank=True, null=True, verbose_name='الانتظار الفعلي (دقيقة)')),
                ('service_duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='مدة الخدمة (دقيقة)')),
                ('queue_position', models.IntegerField(default=0, verbose_name='رقم الطابور')),
                ('is_no_show', models.BooleanField(default=False, verbose_name='لم يحضر')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='سبب الإلغاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_history', to='clinic.appointment', verbose_name='الموعد')),
            ],
            options={
                'verbose_name': 'سجل طابور',
                'verbose_name_plural': 'سجلات الطابور',
                'ordering': ['-scheduled_start_time'],
                'indexes': [models.Index(fields=['-scheduled_start_time'], name='clinic_queu_schedul_232541_idx'), models.Index(fields=['queue_position'], name='clinic_queu_queue_p_5b1e86_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueueStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('total_appointments', models.IntegerField(default=0, verbose_name='إجمالي المواعيد')),
                ('completed_appointments', models.IntegerField(default=0, verbose_name='المواعيد المكتملة')),
                ('average_wait_minutes', models.IntegerField(default=0, verbose_name='متوسط الانتظار (دقيقة)')),
                ('average_service_duration_minutes', models.IntegerField(default=0, verbose_name='متوسط مدة الخدمة (دقيقة)')),
                ('min_wait_minutes', models.IntegerField(default=0, verbose_name='الحد الأدنى للانتظار (دقيقة)')),
                ('max_wait_minutes', models.IntegerField(default=0, verbose_name='الحد الأقصى للانتظار (دقيقة)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_stats', to='clinic.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'إحصائية طابور',
                'verbose_name_plural': 'إحصائيات الطابور',
                'ordering': ['-appointment_date'],
                'indexes': [models.Index(fields=['service', 'appointment_date'], name='clinic_queu_service_a2b845_idx'), models.Index(fields=['-appointment_date'], name='clinic_queu_appoint_53e442_idx')],
                'unique_together': {('service', 'appointment_date')},
            },
        ),
    ]
