# Generated by Django 6.0 on 2025-12-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_queuehistory_queuestatistics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
